apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: <PASSWORD>
  PGDATA: /var/lib/postgresql/data/pgdata
